import React from 'react';

interface ImageGenResultDisplayProps {
  outputData?: any;
  errorMessage?: string | null;
}

const ImageGenResultDisplay: React.FC<ImageGenResultDisplayProps> = ({ outputData, errorMessage }) => {
  const imageUrl = typeof outputData?.image_url === 'string' ? outputData.image_url : '';

  const handleDownload = () => {
    if (!imageUrl) return;
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = 'autoflow-image.png';
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  if (errorMessage) {
    return (
      <div className="space-y-2">
        <span className="text-[10px] font-black uppercase tracking-widest text-rose-500">Image Gen Error</span>
        <div className="rounded-2xl border border-rose-200 dark:border-rose-900/30 bg-rose-50 dark:bg-rose-900/20 p-3 text-xs text-rose-600 dark:text-rose-300 font-mono whitespace-pre-wrap break-words">
          {errorMessage}
        </div>
      </div>
    );
  }

  if (!imageUrl) return null;

  return (
    <div className="space-y-3">
      <span className="text-[10px] font-black uppercase tracking-widest text-amber-500">Generated Image</span>
      <div className="overflow-hidden rounded-3xl border border-amber-100 dark:border-amber-900/30 bg-amber-50/50 dark:bg-amber-900/10">
        <img src={imageUrl} alt="Generated by Image Gen node" className="w-full object-contain bg-slate-950/5" />
      </div>
      <button
        type="button"
        onClick={handleDownload}
        className="w-full rounded-2xl bg-slate-900 dark:bg-slate-100 px-4 py-2.5 text-xs font-black text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-200 transition-colors"
      >
        Download Image
      </button>
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-3 text-[11px] text-slate-500 dark:text-slate-400 space-y-2">
        <div><span className="font-bold text-slate-700 dark:text-slate-200">Model:</span> {outputData?.model || 'unknown'}</div>
        <div><span className="font-bold text-slate-700 dark:text-slate-200">Dimensions:</span> {outputData?.width || '?'} x {outputData?.height || '?'}</div>
        <div><span className="font-bold text-slate-700 dark:text-slate-200">Prompt:</span> {outputData?.prompt_used || ''}</div>
        {outputData?.revised_prompt && (
          <div><span className="font-bold text-slate-700 dark:text-slate-200">Revised prompt:</span> {outputData.revised_prompt}</div>
        )}
      </div>
    </div>
  );
};

export default ImageGenResultDisplay;
