export interface NodeDefinition {
  type: string;
  label: string;
  category: 'trigger' | 'action' | 'transform' | 'input_output' | 'utility' | 'ai';
  description: string;
  default_config: Record<string, any>;
  is_dummy: boolean;
  icon?: string;
  color?: string;
  badge?: string;
  phase?: number;
}

export const NODE_LIBRARY: Record<string, NodeDefinition[]> = {
  trigger: [
    {
      type: 'manual_trigger',
      label: 'Manual Trigger',
      category: 'trigger',
      description: 'Start the workflow manually with one click.',
      default_config: {},
      is_dummy: false,
    },
    {
      type: 'form_trigger',
      label: 'Form Trigger',
      category: 'trigger',
      description: 'Trigger the workflow when a form is submitted.',
      default_config: {
        form_title: 'Form Submission',
        form_description: '',
        fields: [
          {
            name: 'email',
            label: 'Email',
            type: 'email',
            required: true,
          },
        ],
      },
      is_dummy: false,
    },
    {
      type: 'webhook_trigger',
      label: 'Webhook Trigger',
      category: 'trigger',
      description: 'Trigger the workflow via an HTTP request.',
      default_config: {
        path: '',
        method: 'POST',
      },
      is_dummy: false,
    },
    {
      type: 'schedule_trigger',
      label: 'Schedule Trigger',
      category: 'trigger',
      description: 'Trigger the workflow on a recurring schedule with simple trigger rules.',
      default_config: {
        timezone: 'Asia/Kolkata',
        enabled: true,
        rules: [
          {
            id: 'rule_1',
            interval: 'hours',
            every: 1,
            trigger_minute: 0,
            enabled: true,
          },
        ],
      },
      is_dummy: false,
    },
    {
      type: 'workflow_trigger',
      label: 'Workflow Trigger',
      category: 'trigger',
      description: 'Used in child workflows called by Execute Workflow node.',
      default_config: {
        input_data_mode: 'accept_all',
        input_schema: [],
        json_example: '',
      },
      is_dummy: false,
    },
  ],
  input_output: [
    {
      type: 'http_request',
      label: 'HTTP Request',
      category: 'input_output',
      description: 'Call external APIs with any HTTP method and auth mode.',
      default_config: {
        url: '',
        method: 'GET',
        auth_mode: 'none',
        credential_id: '',
        bearer_token: '',
        bearer_prefix: 'Bearer',
        username: '',
        password: '',
        api_key_name: 'x-api-key',
        api_key_value: '',
        api_key_in: 'header',
        api_key_prefix: '',
        headers_json: '{}',
        query_json: '{}',
        body_type: 'none',
        body_json: '{}',
        body_form_json: '{}',
        body_raw: '',
        timeout_seconds: 30,
        follow_redirects: true,
        continue_on_fail: false,
        response_format: 'auto',
      },
      is_dummy: false,
    },
    {
      type: 'file_read',
      label: 'File Read',
      category: 'input_output',
      description: 'Read a local file and parse it as text, JSON, CSV, lines, or base64.',
      default_config: {
        file_path: '',
        parse_as: 'auto',
        encoding: 'utf-8',
        max_bytes: 5242880,
        include_metadata: true,
        csv_delimiter: '',
      },
      is_dummy: false,
    },
    {
      type: 'file_write',
      label: 'File Create/Write',
      category: 'input_output',
      description: 'Create or update a local file using workflow data or fixed content.',
      default_config: {
        file_path: '',
        content_source: 'input',
        input_key: '',
        content_text: '',
        input_format: 'auto',
        write_mode: 'create',
        encoding: 'utf-8',
        create_dirs: true,
      },
      is_dummy: false,
    },
  ],
  action: [
    {
      type: 'execute_workflow',
      label: 'Execute Workflow',
      category: 'action',
      description: 'Call another workflow and use its final output.',
      default_config: {
        source: 'database',
        workflow_id: '',
        workflow_json: '',
        workflow_inputs: [],
        mode: 'run_once',
      },
      is_dummy: false,
    },
    {
      type: 'get_gmail_message',
      label: 'Get Gmail Message',
      category: 'action',
      description: 'Retrieve messages from a Gmail account.',
      default_config: {
        credential_id: '',
        folder: 'INBOX',
        query: '',
        limit: '10',
        unread_only: false,
        include_body: false,
        mark_as_read: false,
      },
      is_dummy: false,
      icon: 'gmail',
      color: '#ea4335',
    },
    {
      type: 'send_gmail_message',
      label: 'Send Gmail Message',
      category: 'action',
      description: 'Send an email through a Gmail account.',
      default_config: {
        credential_id: '',
        to: '',
        cc: '',
        bcc: '',
        reply_to: '',
        subject: '',
        body: '',
        image: '',
        is_html: false,
      },
      is_dummy: false,
      icon: 'gmail',
      color: '#ea4335',
    },
    {
      type: 'create_gmail_draft',
      label: 'Create Gmail Draft',
      category: 'action',
      description: 'Create a draft email in Gmail.',
      default_config: {
        credential_id: '',
        to: '',
        subject: '',
        body: '',
      },
      is_dummy: false,
      icon: 'gmail',
      color: '#ea4335',
    },
    {
      type: 'add_gmail_label',
      label: 'Add Gmail Label',
      category: 'action',
      description: 'Find or create a Gmail label and apply it to a message.',
      default_config: {
        credential_id: '',
        message_id: '',
        label_name: '',
      },
      is_dummy: false,
      icon: 'gmail',
      color: '#ea4335',
    },
    {
      type: 'create_google_sheets',
      label: 'Create Google Sheets',
      category: 'action',
      description: 'Create a new Google Spreadsheet.',
      default_config: {
        credential_id: '',
        title: '',
        sheet_name: '',
        columns: [],
      },
      is_dummy: false,
      icon: 'sheets',
    },
    {
      type: 'read_google_sheets',
      label: 'Read Google Sheets',
      category: 'action',
      description: 'Read rows from a Google Sheets worksheet.',
      default_config: {
        credential_id: '',
        spreadsheet_source_type: 'id',
        spreadsheet_id: '',
        spreadsheet_url: '',
        sheet_name: 'Sheet1',
        range: '',
        first_row_as_header: true,
        include_empty_rows: false,
        max_rows: '',
      },
      is_dummy: false,
      icon: 'sheets',
    },
    {
      type: 'search_update_google_sheets',
      label: 'Google Sheets Row/Column Ops',
      category: 'action',
      description: 'Append, delete, overwrite, upsert rows, and add/delete columns.',
      default_config: {
        credential_id: '',
        spreadsheet_source_type: 'id',
        spreadsheet_id: '',
        spreadsheet_url: '',
        sheet_name: 'Sheet1',
        operation: 'upsert_row',
        key_column: '',
        key_value: '',
        append_columns: [],
        append_values: [],
        search_column: '',
        search_value: '',
        update_mappings: [],
        columns_to_add: [],
        columns_to_delete: [],
        ensure_columns: [],
        update_column: '',
        update_value: '',
        auto_create_headers: true,
        upsert_if_not_found: false,
      },
      is_dummy: false,
      icon: 'sheets',
    },
    {
      type: 'create_google_docs',
      label: 'Create Google Docs',
      category: 'action',
      description: 'Create a new Google Doc.',
      default_config: {
        credential_id: '',
        title: '',
        initial_content: '',
      },
      is_dummy: false,
      icon: 'docs',
    },
    {
      type: 'read_google_docs',
      label: 'Read Google Docs',
      category: 'action',
      description: 'Read text content from a Google Doc.',
      default_config: {
        credential_id: '',
        document_source_type: 'id',
        document_id: '',
        document_url: '',
        max_characters: '',
        include_raw_json: false,
      },
      is_dummy: false,
      icon: 'docs',
    },
    {
      type: 'update_google_docs',
      label: 'Update Google Docs',
      category: 'action',
      description: 'Append or replace content in a Google Doc.',
      default_config: {
        credential_id: '',
        document_id: '',
        operation: 'append_text',
        text: '',
        image: '',
        match_text: '',
        match_case: false,
      },
      is_dummy: false,
      icon: 'docs',
    },
    {
      type: 'telegram',
      label: 'Telegram Message',
      category: 'action',
      description: 'Send a message via Telegram.',
      default_config: {
        credential_id: '',
        message: '',
        image: '',
        parse_mode: '',
      },
      is_dummy: false,
      icon: 'telegram',
    },
    {
      type: 'whatsapp',
      label: 'WhatsApp Message',
      category: 'action',
      description: 'Send a message via WhatsApp Cloud API.',
      default_config: {
        credential_id: '',
        to_number: '',
        template_name: '',
        template_params: [],
        language_code: 'en_US',
      },
      is_dummy: false,
      icon: 'whatsapp',
    },
    {
      type: 'slack_send_message',
      label: 'Slack Message',
      category: 'action',
      description: 'Send a message to Slack via Incoming Webhook.',
      default_config: {
        credential_id: '',
        message: '',
      },
      is_dummy: false,
      icon: 'slack',
    },
    {
      type: 'linkedin',
      label: 'LinkedIn Post',
      category: 'action',
      description: 'Create a post on LinkedIn.',
      default_config: {
        credential_id: '',
        post_text: '',
        image: '',
        visibility: 'PUBLIC',
      },
      is_dummy: false,
      icon: 'linkedin',
    },
  ],
  transform: [
    {
      type: 'if_else',
      label: 'If Else',
      category: 'transform',
      description: 'Split the workflow based on conditions.',
      default_config: {
        condition_type: 'AND',
        conditions: [
          {
            field: '',
            operator: 'equals',
            value: '',
            value_mode: 'literal',
            value_field: '',
            case_sensitive: true,
          },
        ],
      },
      is_dummy: false,
    },
    {
      type: 'switch',
      label: 'Switch',
      category: 'transform',
      description: 'Route the workflow to multiple paths.',
      default_config: {
        field: '',
        cases: [
          {
            label: '',
            operator: 'equals',
            value: '',
          },
        ],
        default_case: 'default',
      },
      is_dummy: false,
    },
    {
      type: 'merge',
      label: 'Merge',
      category: 'transform',
      description: 'n8n-style merge for append, by-position, by-fields, or choosing one input.',
      default_config: {
        mode: 'append',
        input_count: 2,
        choose_branch: 'input1',
        output_key: 'merged',
        input_1_handle: 'input1',
        input_2_handle: 'input2',
        join_type: 'inner',
        input_1_field: '',
        input_2_field: '',
      },
      is_dummy: false,
    },
    {
      type: 'filter',
      label: 'Filter',
      category: 'transform',
      description: 'Remove items from the data stream.',
      default_config: {
        input_key: '',
        logic: 'and',
        conditions: [
          {
            id: 'condition_1',
            field: '',
            operator: 'equals',
            data_type: 'string',
            value_mode: 'literal',
            value_field: '',
            value: '',
            case_sensitive: true,
            join_with_previous: 'and',
          },
        ],
      },
      is_dummy: false,
    },
    {
      type: 'limit',
      label: 'Limit',
      category: 'transform',
      description: 'Keep only a fixed window of items from an array.',
      default_config: {
        input_key: '',
        limit: 10,
        offset: 0,
        start_from: 'start',
      },
      is_dummy: false,
    },
    {
      type: 'sort',
      label: 'Sort',
      category: 'transform',
      description: 'Sort items in an array by value or object field.',
      default_config: {
        input_key: '',
        sort_by: '',
        order: 'asc',
        data_type: 'auto',
        nulls: 'last',
        case_sensitive: false,
      },
      is_dummy: false,
    },
    {
      type: 'datetime_format',
      label: 'Date Time Format',
      category: 'transform',
      description: 'Standardize date and time formats.',
      default_config: {
        field: '',
        output_format: '%Y-%m-%d',
      },
      is_dummy: false,
    },
    {
      type: 'split_in',
      label: 'Split In',
      category: 'transform',
      description: 'Iterate through a collection of items.',
      default_config: {
        input_key: '',
      },
      is_dummy: false,
    },
    {
      type: 'split_out',
      label: 'Split Out',
      category: 'transform',
      description: 'Collect iterated items.',
      default_config: {
        output_key: 'results',
      },
      is_dummy: false,
    },
    {
      type: 'aggregate',
      label: 'Aggregate',
      category: 'transform',
      description: 'Combine multiple items into one array.',
      default_config: {
        input_key: '',
        field: '',
        operation: 'sum',
        output_key: '',
      },
      is_dummy: false,
    },
    {
      type: 'delay',
      label: 'Delay',
      category: 'transform',
      description: 'Pause workflow for a duration, then continue.',
      default_config: {
        wait_mode: 'after_interval',
        amount: '1',
        unit: 'minutes',
        until_datetime: '',
        timezone: 'Asia/Kolkata',
      },
      is_dummy: false,
    },
  ],
  utility: [
    {
      type: 'code',
      label: 'Code',
      category: 'utility',
      description: 'Run Python or JavaScript against the incoming JSON payload.',
      default_config: {
        language: 'python',
        code: '# input_data is available as a dict\n# assign your result to: output\noutput = input_data',
      },
      is_dummy: false,
      color: 'purple',
      badge: '</>',
    },
  ],
  ai: [
    {
      type: 'ai_agent',
      label: 'AI Agent',
      category: 'ai',
      description: 'Advanced AI processing and analysis.',
      default_config: {
        system_prompt: '',
        command: '',
        response_enhancement: 'auto',
      },
      is_dummy: false,
    },
    {
      type: 'image_gen',
      label: 'Image Gen',
      category: 'ai',
      description: 'Generate an image with OpenAI and pass base64 output downstream.',
      default_config: {
        credential_id: '',
        model: 'dall-e-3',
        prompt: '',
        size: '1024x1024',
        quality: 'standard',
        style: 'vivid',
      },
      is_dummy: false,
      icon: 'image',
    },
    {
      type: 'chat_model_openai',
      label: 'Chat Model (OpenAI)',
      category: 'ai',
      description: 'Configure an OpenAI chat model.',
      default_config: {
        credential_id: '',
        model: 'gpt-4o',
        temperature: 0.7,
      },
      is_dummy: false,
    },
    {
      type: 'chat_model_groq',
      label: 'Chat Model (Groq)',
      category: 'ai',
      description: 'Configure a Groq chat model.',
      default_config: {
        credential_id: '',
        model: 'llama-3.3-70b-versatile',
        temperature: 0.7,
      },
      is_dummy: false,
    },
  ],
};

export const CATEGORY_STYLES = {
  trigger: 'border-l-4 border-emerald-500 bg-white text-slate-700 hover:bg-slate-50',
  action: 'border-l-4 border-blue-500 bg-white text-slate-700 hover:bg-slate-50',
  transform: 'border-l-4 border-amber-500 bg-white text-slate-700 hover:bg-slate-50',
  input_output: 'border-l-4 border-cyan-500 bg-white text-slate-700 hover:bg-slate-50',
  utility: 'border-l-4 border-purple-500 bg-white text-slate-700 hover:bg-slate-50',
  ai: 'border-l-4 border-purple-500 bg-white text-slate-700 hover:bg-slate-50',
};

export const CATEGORY_ACCENTS = {
  trigger: '#10b981', // emerald-500
  action: '#3b82f6', // blue-500
  transform: '#f59e0b', // amber-500
  input_output: '#06b6d4', // cyan-500
  utility: '#a855f7', // purple-500
  ai: '#a855f7', // purple-500
};
